### ISSUE TITLE
Error in TMFC006 YAML

### ISSUE THREAD

**Issue by andytiller** [tmforum-rand/TMForum-ODA-Ready-for-publication#8]
TMF633 listed twice in https://github.com/tmforum-rand/TMForum-ODA-Ready-for-publication/blob/v1beta2/specifications/TMFC006-ServiceCatalogManagement/TMFC006-ServiceCatalogManagement.yaml

Second one should be TMF657.

**Comment by hvaughanattmforum** [comment]
Resolved.

Thanks

**Comment by hvaughanattmforum** [comment]
Closed and verified
